Repository Harmos274/gotrans, pull requests merged in 2023-01, with the labels that each got.

#1 Add warehouse ouputs (visual & textual)
  gotrans.go
  parse_input_file.go
  show_warehouse.go
  warehouse/warehouse.go
Labels: enhancement

#5 Improve run section of readme
  README.md
Labels: documentation

#4 Add help flags and argument parsing
  gotrans.go
Labels: enhancement

#2 Implement pathfinding
  gotrans.go
  parse_input_file.go
  show_warehouse.go
  warehouse/al.go
  warehouse/warehouse.go
Labels: enhancement

#6 Report events from clearWarehouse
  gotrans.go
  warehouse/event.go
  warehouse/warehouse.go
Labels: enhancement

#7 Add event printing
  gotrans.go
  show_warehouse.go
  warehouse/event.go
Labels: enhancement

#9 Finish readme and add component diagram
  README.md
  gotrans_component_diagram.png
Labels: documentation, enhancement

#10 Add truck movement
  gotrans.go
  show_warehouse.go
  warehouse/al.go
  warehouse/event.go
  warehouse/warehouse.go
Labels: enhancement
